spring:
  security:
    oauth2:
      client:
        provider:
          azure-ad:
            authorization-uri: https://login.microsoftonline.com/da4288f0-d762-494d-a5ac-3f20808dd7c4/oauth2/v2.0/authorize
            token-uri: https://login.microsoftonline.com/da4288f0-d762-494d-a5ac-3f20808dd7c4/oauth2/v2.0/token
            jwk-set-uri: https://login.microsoftonline.com/common/discovery/v2.0/keys
        registration:
          azure-client:
            provider: azure-ad
            client-id: a42218dc-eb48-40b2-89c6-72ac80b80d20
            client-secret: hBg8Q~Cjals_hGha1G-b8GKkNyOfgmDK6eUAddBE
            authorization-grant-type: authorization_code
            redirect-uri: '{baseUrl}/login/oauth2/code/'
            scope: openid,profile            
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://kp-tc-mysql.mysql.database.azure.com:3306/tc_db?useSSL=true
    username: kp_admin
    password: Pass@123
    driver-class-name: com.mysql.cj.jdbc.Driver
    
azure:
  application-insights:
    instrumentation-key: fbe82342-9764-42e2-8f41-6dab6a494f35
    
server:
  forward-headers-strategy: native
  
tc:
  site-id: tradecollaborationengine.sharepoint.com,851fe44e-f427-4478-bbf2-17451f4fe782,799be97d-8a9e-420a-a985-b461f43bb482
  shared-document-list-id: 29bbaa17-b9ab-4695-a794-a671921894a0
  shared-document-drive-id: b!TuQfhSf0eES78hdFH0_ngn3pm3meigpCqYW0YfQ7tIIXqrspq7mVRqeUpnGSGJSg
  